server:
  port: 8080

spring:
  application:
    name: user-service

# Logging level
logging:
  level:
    root: INFO
    com.pooja: DEBUG

# Swagger / OpenAPI config via springdoc
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
